apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: pod-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: pod-{{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: us-central1-docker.pkg.dev/thinksystemio/images/{{ .Values.name }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.name }}
spec:
  selector:
    app: pod-{{ .Values.name }}
  ports:
    - port: 80
      targetPort: 80
